
name: multistage pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:


jobs:
  job1: 
    if: github.repository == 'https://github.com/salmanlari/terraform_code.git'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "hello" 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
  job2: 
   runs-on: ubuntu-latest
   needs: job1
   steps:
     - uses: actions/checkout@v1
     - run: echo "world"   
       env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}



  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - uses: actions/checkout@v1
      - run: echo "hello" 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - uses: actions/checkout@v1
      - run: echo "world" 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}