name: terraform execution

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1
        name: Download codebase


      - name: terraform plan
        uses: dflook/terraform-plan@v1


    # - name: terraform apply
    #     uses: dflook/terraform-apply@v1

