name: terraform execution
on:
  pull_request:
  push: [master]

jobs:
  terraform:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1
      name: Download codebase


    - name: terraform plan
      uses: dflook/terraform-plan@v1


    # - name: terraform apply
    #     uses: dflook/terraform-apply@v1

