name:  user input manual workflows

on:
  workflow_dispatch:
    inputs:
     name:
        type: choice
        description: choose one
        options:
          - salman
          - lari
     message:
        required: true
  #
  #

jobs:
  job:  
    runs-on: ubuntu-latest
    steps:
    - name: print
      run: echo "hello"
#       - run: echo "${{github.event.inputs.name"}} ${{github.event.inputs.message"}}"
